default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: localhost
development:
  <<: *default
  database: study_soup_development
test:
  <<: *default
  database: study_soup_test
staging:
  <<: *default
  database: study_soup_staging
  username: <%= ENV['PRODUCTION_POSTGRES_USER'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASS'] %>
  port: 5433
  host: localhost
production:
  <<: *default
  database: study_soup_production
  username: <%= ENV['PRODUCTION_POSTGRES_USER'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASS'] %>
  host: <%= ENV['PRODUCTION_POSTGRES_HOST'] %>
  port: 5432
